// demo/react/Paragraph.tsx
import { useNodeViewContext } from '@type-editor/adapter-react';
import { useEffect } from 'react';

export function Paragraph() {
    const { dom, node } = useNodeViewContext();

    useEffect(() => {
        if (!dom) {
            return;
        }

        // Apply paragraph-specific styling directly to the <p> element.
        // Add any custom attributes or styles here.
        dom.style.backgroundImage = 'url(\'/React.svg\')';
        dom.style.backgroundRepeat = 'no-repeat';
        dom.style.backgroundPosition = 'center 0.1rem';
        dom.style.backgroundSize = '1rem 1rem';

        if (node.attrs.align) {
            dom.style.textAlign = node.attrs.align as string;
        }
    }, [dom, node]);

    // No DOM output — the <p> is created by the `as` factory in Editor.tsx.
    // With contentAs: 'self', ProseMirror manages the content directly inside it.
    return null;
}

// demo/vue/Paragraph.vue
<script setup lang="ts">
import { useNodeViewContext } from '@type-editor/adapter-vue'
import { watchEffect } from 'vue'

const { dom, node } = useNodeViewContext()

watchEffect(() => {
    if (!dom) return

    dom.style.backgroundImage = "url('/Vue.svg')"
    dom.style.backgroundRepeat = 'no-repeat'
    dom.style.backgroundPosition = 'center 0.1rem'
    dom.style.backgroundSize = '1rem 1rem'

    if (node.value?.attrs?.align) {
        dom.style.textAlign = node.value.attrs.align as string
    }
})
</script>



<!-- No template output — the <p> is created by the `as` factory in Editor.vue.
     With contentAs: 'self', ProseMirror manages the content directly inside it. -->
<template></template>
